{% set name = "jinja2-humanize-extension" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jinja2_humanize_extension-{{ version }}.tar.gz
  sha256: e7d69b1c20f32815bbec722330ee8af14b1287bb1c2b0afa590dbf031cadeaa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - jinja2
    - humanize >=3.14.0

test:
  imports:
    - jinja2_humanize_extension
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/metwork-framework/jinja2_humanize_extension
  summary: a jinja2 extension to use humanize library inside jinja2 templates
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - peterbygrave
